"""Catalog supported operation behavior and local safety metadata."""

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType

from .models import OperationType, RiskLevel


@dataclass(frozen=True, slots=True)
class OperationSpec:
    type: OperationType
    description: str
    base_risk: RiskLevel
    destructive: bool
    requires_targets: bool
    undo_expected: bool


OPERATION_CATALOG: Mapping[OperationType, OperationSpec] = MappingProxyType(
    {
        OperationType.CREATE_PRIMITIVE: OperationSpec(
            OperationType.CREATE_PRIMITIVE,
            "Create a supported mesh primitive.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.DELETE_OBJECTS: OperationSpec(
            OperationType.DELETE_OBJECTS,
            "Delete existing objects by context-issued target ID.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.DUPLICATE_OBJECTS: OperationSpec(
            OperationType.DUPLICATE_OBJECTS,
            "Duplicate existing objects with a bounded count and offset.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.SET_TRANSFORM: OperationSpec(
            OperationType.SET_TRANSFORM,
            "Set or offset object transforms.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.CREATE_MATERIAL: OperationSpec(
            OperationType.CREATE_MATERIAL,
            "Create a basic Principled BSDF material.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.ASSIGN_MATERIAL: OperationSpec(
            OperationType.ASSIGN_MATERIAL,
            "Assign a referenced material to objects.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.ADD_LIGHT: OperationSpec(
            OperationType.ADD_LIGHT,
            "Add a supported Blender light.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.ADD_CAMERA: OperationSpec(
            OperationType.ADD_CAMERA,
            "Add a camera and optionally make it active.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.RENAME_OBJECTS: OperationSpec(
            OperationType.RENAME_OBJECTS,
            "Rename existing objects with explicit target-to-name mappings.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.MOVE_TO_COLLECTION: OperationSpec(
            OperationType.MOVE_TO_COLLECTION,
            "Move existing objects to an existing collection.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.SET_MATERIAL_PROPERTIES: OperationSpec(
            OperationType.SET_MATERIAL_PROPERTIES,
            "Update a referenced Principled BSDF material.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.CREATE_COLLECTION: OperationSpec(
            OperationType.CREATE_COLLECTION,
            "Create a collection under the scene or a referenced parent collection.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.SET_LIGHT_PROPERTIES: OperationSpec(
            OperationType.SET_LIGHT_PROPERTIES,
            "Update referenced Blender light objects.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.SET_CAMERA_PROPERTIES: OperationSpec(
            OperationType.SET_CAMERA_PROPERTIES,
            "Update referenced camera objects and optionally make them active.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.ADD_MODIFIER: OperationSpec(
            OperationType.ADD_MODIFIER,
            "Add a supported non-applied modifier to mesh objects.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.SET_MODIFIER_PROPERTIES: OperationSpec(
            OperationType.SET_MODIFIER_PROPERTIES,
            "Update supported properties on existing object modifiers.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_TEXT_OBJECT: OperationSpec(
            OperationType.CREATE_TEXT_OBJECT,
            "Create a Blender text object.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.SET_OBJECT_VISIBILITY: OperationSpec(
            OperationType.SET_OBJECT_VISIBILITY,
            "Show or hide objects in viewport and render output.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.IMPORT_ASSET: OperationSpec(
            OperationType.IMPORT_ASSET,
            "Import a supported local asset file.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.LINK_OR_APPEND_BLEND_DATA: OperationSpec(
            OperationType.LINK_OR_APPEND_BLEND_DATA,
            "Link or append explicit objects or collections from a local blend file.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.BOOLEAN_OPERATION: OperationSpec(
            OperationType.BOOLEAN_OPERATION,
            "Create a controlled non-applied Boolean modifier between two mesh objects.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.JOIN_OBJECTS: OperationSpec(
            OperationType.JOIN_OBJECTS,
            "Join mesh objects into one generated mesh object.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.SEPARATE_OBJECTS: OperationSpec(
            OperationType.SEPARATE_OBJECTS,
            "Separate mesh objects into generated mesh objects by material or loose parts.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.CREATE_MATERIAL_PRESET: OperationSpec(
            OperationType.CREATE_MATERIAL_PRESET,
            "Create a bounded material preset with controlled shader parameters.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.CREATE_PROCEDURAL_MATERIAL: OperationSpec(
            OperationType.CREATE_PROCEDURAL_MATERIAL,
            "Create a bounded procedural material template.",
            RiskLevel.LOW,
            False,
            False,
            True,
        ),
        OperationType.CREATE_SHADER_NODE: OperationSpec(
            OperationType.CREATE_SHADER_NODE,
            "Create an allowlisted shader node inside a referenced material.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.SET_SHADER_NODE_VALUE: OperationSpec(
            OperationType.SET_SHADER_NODE_VALUE,
            "Set a bounded value on an allowlisted shader node socket.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.CONNECT_SHADER_NODES: OperationSpec(
            OperationType.CONNECT_SHADER_NODES,
            "Connect allowlisted shader node sockets inside one material.",
            RiskLevel.LOW,
            False,
            True,
            True,
        ),
        OperationType.REMOVE_SHADER_NODE: OperationSpec(
            OperationType.REMOVE_SHADER_NODE,
            "Remove an assistant-created shader node from a material graph.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.DISCONNECT_SHADER_LINK: OperationSpec(
            OperationType.DISCONNECT_SHADER_LINK,
            "Disconnect one explicit shader link from a material graph.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SHADER_COLOR_RAMP: OperationSpec(
            OperationType.CREATE_SHADER_COLOR_RAMP,
            "Create a bounded color ramp shader node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.SET_SHADER_COLOR_RAMP: OperationSpec(
            OperationType.SET_SHADER_COLOR_RAMP,
            "Update bounded color ramp stops on an explicit shader node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SHADER_MIX_CHAIN: OperationSpec(
            OperationType.CREATE_SHADER_MIX_CHAIN,
            "Create a known safe shader subgraph template.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SHADER_GRAPH_TEMPLATE: OperationSpec(
            OperationType.CREATE_SHADER_GRAPH_TEMPLATE,
            "Create a controlled shader graph template.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.VALIDATE_MATERIAL_OUTPUT: OperationSpec(
            OperationType.VALIDATE_MATERIAL_OUTPUT,
            "Validate or repair a material output shader connection.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.LOAD_IMAGE_TEXTURE: OperationSpec(
            OperationType.LOAD_IMAGE_TEXTURE,
            "Load a local or HTTPS image texture as a Blender image datablock.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.CREATE_IMAGE_TEXTURE_NODE: OperationSpec(
            OperationType.CREATE_IMAGE_TEXTURE_NODE,
            "Attach a loaded image texture to a referenced material.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.SET_TEXTURE_MAPPING: OperationSpec(
            OperationType.SET_TEXTURE_MAPPING,
            "Set projection and mapping values on a controlled image texture node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.ASSIGN_UV_MAP: OperationSpec(
            OperationType.ASSIGN_UV_MAP,
            "Assign an existing UV map to a controlled texture node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_UV_MAP: OperationSpec(
            OperationType.CREATE_UV_MAP,
            "Create a new UV map on mesh objects.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.UNWRAP_UV_MAP: OperationSpec(
            OperationType.UNWRAP_UV_MAP,
            "Generate bounded UV coordinates for explicit mesh targets.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.PACK_UV_ISLANDS: OperationSpec(
            OperationType.PACK_UV_ISLANDS,
            "Normalize and pack UV coordinates on explicit mesh targets.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.IMPORT_PBR_TEXTURE_SET: OperationSpec(
            OperationType.IMPORT_PBR_TEXTURE_SET,
            "Import explicitly listed PBR texture files into a texture set.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.CREATE_PBR_MATERIAL: OperationSpec(
            OperationType.CREATE_PBR_MATERIAL,
            "Build a controlled PBR material from approved image texture inputs.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.SET_PBR_TEXTURE_ROLE: OperationSpec(
            OperationType.SET_PBR_TEXTURE_ROLE,
            "Correct the role of an imported PBR texture inside a texture set.",
            RiskLevel.MEDIUM,
            False,
            False,
            True,
        ),
        OperationType.GENERATE_TEXTURE_IMAGE: OperationSpec(
            OperationType.GENERATE_TEXTURE_IMAGE,
            "Create a generated texture image from bounded prompt metadata.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.SAVE_GENERATED_TEXTURE: OperationSpec(
            OperationType.SAVE_GENERATED_TEXTURE,
            "Save an explicit generated image to an explicit local output path.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.ATTACH_GENERATED_TEXTURE: OperationSpec(
            OperationType.ATTACH_GENERATED_TEXTURE,
            "Attach a generated texture image to a material node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_PAINT_IMAGE: OperationSpec(
            OperationType.CREATE_PAINT_IMAGE,
            "Create a bounded image datablock for texture painting.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.ASSIGN_PAINT_SLOT: OperationSpec(
            OperationType.ASSIGN_PAINT_SLOT,
            "Attach a paint image to a material and UV target.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.APPLY_TEXTURE_PAINT_STROKES: OperationSpec(
            OperationType.APPLY_TEXTURE_PAINT_STROKES,
            "Apply bounded UV-space paint strokes to an explicit image.",
            RiskLevel.HIGH,
            True,
            False,
            True,
        ),
        OperationType.FILL_TEXTURE_REGION: OperationSpec(
            OperationType.FILL_TEXTURE_REGION,
            "Fill a bounded UV-space image region with a controlled color.",
            RiskLevel.MEDIUM,
            True,
            False,
            True,
        ),
        OperationType.CREATE_BAKE_TARGET_IMAGE: OperationSpec(
            OperationType.CREATE_BAKE_TARGET_IMAGE,
            "Create a bounded image datablock for texture baking output.",
            RiskLevel.HIGH,
            False,
            False,
            True,
        ),
        OperationType.BAKE_TEXTURE_PASS: OperationSpec(
            OperationType.BAKE_TEXTURE_PASS,
            "Bake a bounded deterministic texture pass into an explicit target image.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.ASSIGN_BAKED_TEXTURE: OperationSpec(
            OperationType.ASSIGN_BAKED_TEXTURE,
            "Attach a baked texture image to a material node.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.ADD_DISPLACE_MODIFIER: OperationSpec(
            OperationType.ADD_DISPLACE_MODIFIER,
            "Add a non-applied procedural Displace modifier to mesh objects.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.ADD_SMOOTH_MODIFIER: OperationSpec(
            OperationType.ADD_SMOOTH_MODIFIER,
            "Add a non-applied Smooth modifier to mesh objects.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.ADD_REMESH_MODIFIER: OperationSpec(
            OperationType.ADD_REMESH_MODIFIER,
            "Add a non-applied Remesh modifier to mesh objects.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.SCULPT_SMOOTH_REGION: OperationSpec(
            OperationType.SCULPT_SMOOTH_REGION,
            "Smooth a bounded mesh region with rollback support.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.APPLY_SCULPT_BRUSH_STROKES: OperationSpec(
            OperationType.APPLY_SCULPT_BRUSH_STROKES,
            "Apply bounded sculpt-like brush strokes to mesh vertex data.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.CREATE_GEOMETRY_NODES_PRESET: OperationSpec(
            OperationType.CREATE_GEOMETRY_NODES_PRESET,
            "Add a controlled Geometry Nodes preset modifier to mesh objects.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.SET_GEOMETRY_NODE_INPUT: OperationSpec(
            OperationType.SET_GEOMETRY_NODE_INPUT,
            "Set a bounded exposed input on a controlled Geometry Nodes preset.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_GEOMETRY_NODE_GROUP_TEMPLATE: OperationSpec(
            OperationType.CREATE_GEOMETRY_NODE_GROUP_TEMPLATE,
            "Create a controlled Geometry Nodes node-group template modifier.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.REMOVE_GEOMETRY_NODES_MODIFIER: OperationSpec(
            OperationType.REMOVE_GEOMETRY_NODES_MODIFIER,
            "Remove an assistant-created Geometry Nodes modifier.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_GENERATED_GEOMETRY_COPY: OperationSpec(
            OperationType.CREATE_GENERATED_GEOMETRY_COPY,
            "Create a generated mesh copy while preserving the original object.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SMOOTHED_COPY: OperationSpec(
            OperationType.CREATE_SMOOTHED_COPY,
            "Create a smoothed generated mesh copy while preserving the original.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_DISPLACED_COPY: OperationSpec(
            OperationType.CREATE_DISPLACED_COPY,
            "Create a displaced generated mesh copy while preserving the original.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_REMESHED_COPY: OperationSpec(
            OperationType.CREATE_REMESHED_COPY,
            "Create a bounded remeshed generated copy while preserving the original.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_DYNAMIC_TOPOLOGY_COPY: OperationSpec(
            OperationType.CREATE_DYNAMIC_TOPOLOGY_COPY,
            "Create a dynamic-topology-style generated copy while preserving the original.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.REPLACE_OBJECT_WITH_GENERATED_COPY: OperationSpec(
            OperationType.REPLACE_OBJECT_WITH_GENERATED_COPY,
            "Hide or replace an original object with an approved generated copy.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.APPLY_GENERATED_MESH_TO_OBJECT: OperationSpec(
            OperationType.APPLY_GENERATED_MESH_TO_OBJECT,
            "Apply a generated mesh to an original object with rollback and preservation.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.CREATE_SCULPT_REGION_FROM_MATERIAL: OperationSpec(
            OperationType.CREATE_SCULPT_REGION_FROM_MATERIAL,
            "Create a named sculpt region from a material assignment.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SCULPT_REGION_FROM_VERTEX_GROUP: OperationSpec(
            OperationType.CREATE_SCULPT_REGION_FROM_VERTEX_GROUP,
            "Create a named sculpt region from a vertex group.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SCULPT_MASK: OperationSpec(
            OperationType.CREATE_SCULPT_MASK,
            "Create a vertex-group based sculpt mask from an approved sculpt region.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.CREATE_FACE_SET_FROM_MATERIAL: OperationSpec(
            OperationType.CREATE_FACE_SET_FROM_MATERIAL,
            "Create a mesh face-set attribute from a material assignment.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_FACE_SET_FROM_VERTEX_GROUP: OperationSpec(
            OperationType.CREATE_FACE_SET_FROM_VERTEX_GROUP,
            "Create a mesh face-set attribute from a vertex group.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.APPLY_SCULPT_REGION_OPERATION: OperationSpec(
            OperationType.APPLY_SCULPT_REGION_OPERATION,
            "Apply a bounded sculpt operation to a named region.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.ADD_MULTIRES_MODIFIER: OperationSpec(
            OperationType.ADD_MULTIRES_MODIFIER,
            "Add a non-applied Multires modifier to mesh objects.",
            RiskLevel.HIGH,
            False,
            True,
            True,
        ),
        OperationType.CREATE_SHAPE_KEY: OperationSpec(
            OperationType.CREATE_SHAPE_KEY,
            "Create a bounded shape key, optionally from a generated copy.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.CREATE_RIG_SAFE_SHAPE_KEY: OperationSpec(
            OperationType.CREATE_RIG_SAFE_SHAPE_KEY,
            "Create a shape key with explicit rig and animation guards.",
            RiskLevel.HIGH,
            True,
            True,
            True,
        ),
        OperationType.SET_SHAPE_KEY_VALUE: OperationSpec(
            OperationType.SET_SHAPE_KEY_VALUE,
            "Set a bounded value on an existing shape key.",
            RiskLevel.MEDIUM,
            False,
            True,
            True,
        ),
        OperationType.CREATE_PREVIEW_IMAGE: OperationSpec(
            OperationType.CREATE_PREVIEW_IMAGE,
            "Create a local preview image datablock for review.",
            RiskLevel.MEDIUM,
            False,
            False,
            True,
        ),
        OperationType.CREATE_RENDER_PREVIEW_IMAGE: OperationSpec(
            OperationType.CREATE_RENDER_PREVIEW_IMAGE,
            "Create a bounded low-resolution render preview image.",
            RiskLevel.MEDIUM,
            False,
            False,
            True,
        ),
    }
)


def get_operation_spec(operation_type: OperationType) -> OperationSpec:
    return OPERATION_CATALOG[operation_type]
