"""Typed records for validated controlled-operation plans."""

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class PlanStatus(StrEnum):
    READY = "ready"
    NEEDS_CLARIFICATION = "needs_clarification"


class OperationType(StrEnum):
    CREATE_PRIMITIVE = "CREATE_PRIMITIVE"
    DELETE_OBJECTS = "DELETE_OBJECTS"
    DUPLICATE_OBJECTS = "DUPLICATE_OBJECTS"
    SET_TRANSFORM = "SET_TRANSFORM"
    CREATE_MATERIAL = "CREATE_MATERIAL"
    ASSIGN_MATERIAL = "ASSIGN_MATERIAL"
    ADD_LIGHT = "ADD_LIGHT"
    ADD_CAMERA = "ADD_CAMERA"
    RENAME_OBJECTS = "RENAME_OBJECTS"
    MOVE_TO_COLLECTION = "MOVE_TO_COLLECTION"
    SET_MATERIAL_PROPERTIES = "SET_MATERIAL_PROPERTIES"
    CREATE_COLLECTION = "CREATE_COLLECTION"
    SET_LIGHT_PROPERTIES = "SET_LIGHT_PROPERTIES"
    SET_CAMERA_PROPERTIES = "SET_CAMERA_PROPERTIES"
    ADD_MODIFIER = "ADD_MODIFIER"
    SET_MODIFIER_PROPERTIES = "SET_MODIFIER_PROPERTIES"
    CREATE_TEXT_OBJECT = "CREATE_TEXT_OBJECT"
    SET_OBJECT_VISIBILITY = "SET_OBJECT_VISIBILITY"
    IMPORT_ASSET = "IMPORT_ASSET"
    LINK_OR_APPEND_BLEND_DATA = "LINK_OR_APPEND_BLEND_DATA"
    BOOLEAN_OPERATION = "BOOLEAN_OPERATION"
    JOIN_OBJECTS = "JOIN_OBJECTS"
    SEPARATE_OBJECTS = "SEPARATE_OBJECTS"
    CREATE_MATERIAL_PRESET = "CREATE_MATERIAL_PRESET"
    CREATE_PROCEDURAL_MATERIAL = "CREATE_PROCEDURAL_MATERIAL"
    CREATE_SHADER_NODE = "CREATE_SHADER_NODE"
    SET_SHADER_NODE_VALUE = "SET_SHADER_NODE_VALUE"
    CONNECT_SHADER_NODES = "CONNECT_SHADER_NODES"
    REMOVE_SHADER_NODE = "REMOVE_SHADER_NODE"
    DISCONNECT_SHADER_LINK = "DISCONNECT_SHADER_LINK"
    CREATE_SHADER_COLOR_RAMP = "CREATE_SHADER_COLOR_RAMP"
    SET_SHADER_COLOR_RAMP = "SET_SHADER_COLOR_RAMP"
    CREATE_SHADER_MIX_CHAIN = "CREATE_SHADER_MIX_CHAIN"
    CREATE_SHADER_GRAPH_TEMPLATE = "CREATE_SHADER_GRAPH_TEMPLATE"
    VALIDATE_MATERIAL_OUTPUT = "VALIDATE_MATERIAL_OUTPUT"
    LOAD_IMAGE_TEXTURE = "LOAD_IMAGE_TEXTURE"
    CREATE_IMAGE_TEXTURE_NODE = "CREATE_IMAGE_TEXTURE_NODE"
    SET_TEXTURE_MAPPING = "SET_TEXTURE_MAPPING"
    ASSIGN_UV_MAP = "ASSIGN_UV_MAP"
    CREATE_UV_MAP = "CREATE_UV_MAP"
    UNWRAP_UV_MAP = "UNWRAP_UV_MAP"
    PACK_UV_ISLANDS = "PACK_UV_ISLANDS"
    IMPORT_PBR_TEXTURE_SET = "IMPORT_PBR_TEXTURE_SET"
    CREATE_PBR_MATERIAL = "CREATE_PBR_MATERIAL"
    SET_PBR_TEXTURE_ROLE = "SET_PBR_TEXTURE_ROLE"
    GENERATE_TEXTURE_IMAGE = "GENERATE_TEXTURE_IMAGE"
    SAVE_GENERATED_TEXTURE = "SAVE_GENERATED_TEXTURE"
    ATTACH_GENERATED_TEXTURE = "ATTACH_GENERATED_TEXTURE"
    CREATE_PAINT_IMAGE = "CREATE_PAINT_IMAGE"
    ASSIGN_PAINT_SLOT = "ASSIGN_PAINT_SLOT"
    APPLY_TEXTURE_PAINT_STROKES = "APPLY_TEXTURE_PAINT_STROKES"
    FILL_TEXTURE_REGION = "FILL_TEXTURE_REGION"
    CREATE_BAKE_TARGET_IMAGE = "CREATE_BAKE_TARGET_IMAGE"
    BAKE_TEXTURE_PASS = "BAKE_TEXTURE_PASS"
    ASSIGN_BAKED_TEXTURE = "ASSIGN_BAKED_TEXTURE"
    ADD_DISPLACE_MODIFIER = "ADD_DISPLACE_MODIFIER"
    ADD_SMOOTH_MODIFIER = "ADD_SMOOTH_MODIFIER"
    ADD_REMESH_MODIFIER = "ADD_REMESH_MODIFIER"
    SCULPT_SMOOTH_REGION = "SCULPT_SMOOTH_REGION"
    APPLY_SCULPT_BRUSH_STROKES = "APPLY_SCULPT_BRUSH_STROKES"
    CREATE_GEOMETRY_NODES_PRESET = "CREATE_GEOMETRY_NODES_PRESET"
    SET_GEOMETRY_NODE_INPUT = "SET_GEOMETRY_NODE_INPUT"
    CREATE_GEOMETRY_NODE_GROUP_TEMPLATE = "CREATE_GEOMETRY_NODE_GROUP_TEMPLATE"
    REMOVE_GEOMETRY_NODES_MODIFIER = "REMOVE_GEOMETRY_NODES_MODIFIER"
    CREATE_GENERATED_GEOMETRY_COPY = "CREATE_GENERATED_GEOMETRY_COPY"
    CREATE_SMOOTHED_COPY = "CREATE_SMOOTHED_COPY"
    CREATE_DISPLACED_COPY = "CREATE_DISPLACED_COPY"
    CREATE_REMESHED_COPY = "CREATE_REMESHED_COPY"
    REPLACE_OBJECT_WITH_GENERATED_COPY = "REPLACE_OBJECT_WITH_GENERATED_COPY"
    CREATE_SCULPT_REGION_FROM_MATERIAL = "CREATE_SCULPT_REGION_FROM_MATERIAL"
    CREATE_SCULPT_REGION_FROM_VERTEX_GROUP = "CREATE_SCULPT_REGION_FROM_VERTEX_GROUP"
    CREATE_SCULPT_MASK = "CREATE_SCULPT_MASK"
    CREATE_FACE_SET_FROM_MATERIAL = "CREATE_FACE_SET_FROM_MATERIAL"
    CREATE_FACE_SET_FROM_VERTEX_GROUP = "CREATE_FACE_SET_FROM_VERTEX_GROUP"
    APPLY_SCULPT_REGION_OPERATION = "APPLY_SCULPT_REGION_OPERATION"
    CREATE_DYNAMIC_TOPOLOGY_COPY = "CREATE_DYNAMIC_TOPOLOGY_COPY"
    APPLY_GENERATED_MESH_TO_OBJECT = "APPLY_GENERATED_MESH_TO_OBJECT"
    ADD_MULTIRES_MODIFIER = "ADD_MULTIRES_MODIFIER"
    CREATE_SHAPE_KEY = "CREATE_SHAPE_KEY"
    CREATE_RIG_SAFE_SHAPE_KEY = "CREATE_RIG_SAFE_SHAPE_KEY"
    SET_SHAPE_KEY_VALUE = "SET_SHAPE_KEY_VALUE"
    CREATE_PREVIEW_IMAGE = "CREATE_PREVIEW_IMAGE"
    CREATE_RENDER_PREVIEW_IMAGE = "CREATE_RENDER_PREVIEW_IMAGE"


class RiskLevel(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass(frozen=True, slots=True)
class Operation:
    operation_id: str
    type: OperationType
    payload: Mapping[str, Any]

    @property
    def target_ids(self) -> tuple[str, ...]:
        raw_targets = self.payload.get("target_ids")
        if isinstance(raw_targets, tuple):
            targets = [value for value in raw_targets if isinstance(value, str)]
        else:
            targets = []

        renames = self.payload.get("renames")
        if isinstance(renames, tuple):
            targets.extend(
                rename["target_id"]
                for rename in renames
                if isinstance(rename, Mapping) and isinstance(rename.get("target_id"), str)
            )

        for key in ("target_id", "cutter_id"):
            value = self.payload.get(key)
            if isinstance(value, str):
                targets.append(value)

        return tuple(dict.fromkeys(targets))


@dataclass(frozen=True, slots=True)
class OperationPlan:
    snapshot_id: str
    status: PlanStatus
    intent_summary: str
    assumptions: tuple[str, ...]
    questions: tuple[str, ...]
    operations: tuple[Operation, ...]


@dataclass(frozen=True, slots=True)
class RiskAssessment:
    level: RiskLevel
    requires_confirmation: bool
    reasons: tuple[str, ...]
    affected_object_count: int
