"""Typed records for validated controlled-operation plans."""

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class PlanStatus(StrEnum):
    READY = "ready"
    NEEDS_CLARIFICATION = "needs_clarification"


class OperationType(StrEnum):
    CREATE_PRIMITIVE = "CREATE_PRIMITIVE"
    DELETE_OBJECTS = "DELETE_OBJECTS"
    DUPLICATE_OBJECTS = "DUPLICATE_OBJECTS"
    SET_TRANSFORM = "SET_TRANSFORM"
    CREATE_MATERIAL = "CREATE_MATERIAL"
    ASSIGN_MATERIAL = "ASSIGN_MATERIAL"
    ADD_LIGHT = "ADD_LIGHT"
    ADD_CAMERA = "ADD_CAMERA"
    RENAME_OBJECTS = "RENAME_OBJECTS"
    MOVE_TO_COLLECTION = "MOVE_TO_COLLECTION"
    SET_MATERIAL_PROPERTIES = "SET_MATERIAL_PROPERTIES"
    CREATE_COLLECTION = "CREATE_COLLECTION"
    SET_LIGHT_PROPERTIES = "SET_LIGHT_PROPERTIES"
    SET_CAMERA_PROPERTIES = "SET_CAMERA_PROPERTIES"
    ADD_MODIFIER = "ADD_MODIFIER"
    SET_MODIFIER_PROPERTIES = "SET_MODIFIER_PROPERTIES"
    CREATE_TEXT_OBJECT = "CREATE_TEXT_OBJECT"
    SET_OBJECT_VISIBILITY = "SET_OBJECT_VISIBILITY"
    IMPORT_ASSET = "IMPORT_ASSET"
    LINK_OR_APPEND_BLEND_DATA = "LINK_OR_APPEND_BLEND_DATA"
    BOOLEAN_OPERATION = "BOOLEAN_OPERATION"
    JOIN_OBJECTS = "JOIN_OBJECTS"
    SEPARATE_OBJECTS = "SEPARATE_OBJECTS"
    CREATE_MATERIAL_PRESET = "CREATE_MATERIAL_PRESET"
    CREATE_PROCEDURAL_MATERIAL = "CREATE_PROCEDURAL_MATERIAL"
    CREATE_SHADER_NODE = "CREATE_SHADER_NODE"
    SET_SHADER_NODE_VALUE = "SET_SHADER_NODE_VALUE"
    CONNECT_SHADER_NODES = "CONNECT_SHADER_NODES"
    REMOVE_SHADER_NODE = "REMOVE_SHADER_NODE"
    DISCONNECT_SHADER_LINK = "DISCONNECT_SHADER_LINK"
    CREATE_SHADER_COLOR_RAMP = "CREATE_SHADER_COLOR_RAMP"
    SET_SHADER_COLOR_RAMP = "SET_SHADER_COLOR_RAMP"
    CREATE_SHADER_MIX_CHAIN = "CREATE_SHADER_MIX_CHAIN"
    CREATE_SHADER_GRAPH_TEMPLATE = "CREATE_SHADER_GRAPH_TEMPLATE"
    VALIDATE_MATERIAL_OUTPUT = "VALIDATE_MATERIAL_OUTPUT"
    CREATE_LAYERED_SHADER_MATERIAL = "CREATE_LAYERED_SHADER_MATERIAL"
    ADD_SHADER_LAYER = "ADD_SHADER_LAYER"
    SET_SHADER_LAYER_MASK = "SET_SHADER_LAYER_MASK"
    REORDER_SHADER_LAYERS = "REORDER_SHADER_LAYERS"
    REMOVE_SHADER_LAYER = "REMOVE_SHADER_LAYER"
    CREATE_PROCEDURAL_PATTERN_NODE_SET = "CREATE_PROCEDURAL_PATTERN_NODE_SET"
    CREATE_EDGE_WEAR_SHADER = "CREATE_EDGE_WEAR_SHADER"
    CREATE_TRIPLANAR_MAPPING_SETUP = "CREATE_TRIPLANAR_MAPPING_SETUP"
    CREATE_OBJECT_SPACE_GRADIENT_SHADER = "CREATE_OBJECT_SPACE_GRADIENT_SHADER"
    CREATE_CURVATURE_STYLE_MASK = "CREATE_CURVATURE_STYLE_MASK"
    EXTRACT_MATERIAL_PALETTE_FROM_IMAGE = "EXTRACT_MATERIAL_PALETTE_FROM_IMAGE"
    CREATE_MATERIAL_FROM_REFERENCE_IMAGE = "CREATE_MATERIAL_FROM_REFERENCE_IMAGE"
    MATCH_MATERIAL_TO_REFERENCE = "MATCH_MATERIAL_TO_REFERENCE"
    CREATE_LOOKDEV_PREVIEW = "CREATE_LOOKDEV_PREVIEW"
    CREATE_GLASS_MATERIAL = "CREATE_GLASS_MATERIAL"
    CREATE_TRANSLUCENT_MATERIAL = "CREATE_TRANSLUCENT_MATERIAL"
    CREATE_EMISSION_MATERIAL = "CREATE_EMISSION_MATERIAL"
    CREATE_VOLUME_MATERIAL = "CREATE_VOLUME_MATERIAL"
    CREATE_TOON_SHADER_MATERIAL = "CREATE_TOON_SHADER_MATERIAL"
    CREATE_ANISOTROPIC_MATERIAL = "CREATE_ANISOTROPIC_MATERIAL"
    REMOVE_UNUSED_ASSISTANT_SHADER_NODES = "REMOVE_UNUSED_ASSISTANT_SHADER_NODES"
    CONSOLIDATE_DUPLICATE_ASSISTANT_MATERIALS = (
        "CONSOLIDATE_DUPLICATE_ASSISTANT_MATERIALS"
    )
    NORMALIZE_SHADER_NODE_LAYOUT = "NORMALIZE_SHADER_NODE_LAYOUT"
    VALIDATE_SHADER_COMPATIBILITY = "VALIDATE_SHADER_COMPATIBILITY"
    REPAIR_BROKEN_SHADER_LINKS = "REPAIR_BROKEN_SHADER_LINKS"
    CREATE_MATERIAL_VARIANT = "CREATE_MATERIAL_VARIANT"
    TAG_MATERIAL_VARIANT = "TAG_MATERIAL_VARIANT"
    CREATE_SHADER_COMPARISON_PREVIEW = "CREATE_SHADER_COMPARISON_PREVIEW"
    ACCEPT_MATERIAL_VARIANT = "ACCEPT_MATERIAL_VARIANT"
    REJECT_MATERIAL_VARIANT = "REJECT_MATERIAL_VARIANT"
    LOAD_IMAGE_TEXTURE = "LOAD_IMAGE_TEXTURE"
    CREATE_IMAGE_TEXTURE_NODE = "CREATE_IMAGE_TEXTURE_NODE"
    SET_TEXTURE_MAPPING = "SET_TEXTURE_MAPPING"
    ASSIGN_UV_MAP = "ASSIGN_UV_MAP"
    CREATE_UV_MAP = "CREATE_UV_MAP"
    UNWRAP_UV_MAP = "UNWRAP_UV_MAP"
    PACK_UV_ISLANDS = "PACK_UV_ISLANDS"
    INSPECT_UV_MAP = "INSPECT_UV_MAP"
    CREATE_UV_DIAGNOSTIC_REPORT = "CREATE_UV_DIAGNOSTIC_REPORT"
    CREATE_UV_OVERLAP_PREVIEW = "CREATE_UV_OVERLAP_PREVIEW"
    CREATE_UV_STRETCH_PREVIEW = "CREATE_UV_STRETCH_PREVIEW"
    MARK_UV_SEAMS_BY_ANGLE = "MARK_UV_SEAMS_BY_ANGLE"
    MARK_UV_SEAMS_BY_MATERIAL = "MARK_UV_SEAMS_BY_MATERIAL"
    MARK_UV_SEAMS_BY_EDGE_SET = "MARK_UV_SEAMS_BY_EDGE_SET"
    CLEAR_UV_SEAMS = "CLEAR_UV_SEAMS"
    CREATE_UV_ISLANDS_FROM_SEAMS = "CREATE_UV_ISLANDS_FROM_SEAMS"
    SMART_PROJECT_UV_MAP = "SMART_PROJECT_UV_MAP"
    CUBE_PROJECT_UV_MAP = "CUBE_PROJECT_UV_MAP"
    CYLINDER_PROJECT_UV_MAP = "CYLINDER_PROJECT_UV_MAP"
    SPHERE_PROJECT_UV_MAP = "SPHERE_PROJECT_UV_MAP"
    CAMERA_PROJECT_UV_MAP = "CAMERA_PROJECT_UV_MAP"
    LIGHTMAP_UNWRAP_UV_MAP = "LIGHTMAP_UNWRAP_UV_MAP"
    SELECT_UV_ISLANDS_BY_MATERIAL = "SELECT_UV_ISLANDS_BY_MATERIAL"
    TRANSFORM_UV_ISLANDS = "TRANSFORM_UV_ISLANDS"
    ALIGN_UV_ISLANDS = "ALIGN_UV_ISLANDS"
    DISTRIBUTE_UV_ISLANDS = "DISTRIBUTE_UV_ISLANDS"
    SCALE_UV_ISLANDS_TO_BOUNDS = "SCALE_UV_ISLANDS_TO_BOUNDS"
    PIN_UV_ISLANDS = "PIN_UV_ISLANDS"
    UNPIN_UV_ISLANDS = "UNPIN_UV_ISLANDS"
    SET_UV_TEXEL_DENSITY = "SET_UV_TEXEL_DENSITY"
    NORMALIZE_UV_TEXEL_DENSITY = "NORMALIZE_UV_TEXEL_DENSITY"
    PACK_UV_ISLANDS_ADVANCED = "PACK_UV_ISLANDS_ADVANCED"
    MOVE_UV_ISLANDS_TO_TILE = "MOVE_UV_ISLANDS_TO_TILE"
    CREATE_UDIM_TILE_LAYOUT = "CREATE_UDIM_TILE_LAYOUT"
    VALIDATE_UDIM_LAYOUT = "VALIDATE_UDIM_LAYOUT"
    RELAX_UV_ISLANDS = "RELAX_UV_ISLANDS"
    MINIMIZE_UV_STRETCH = "MINIMIZE_UV_STRETCH"
    REPAIR_UV_BOUNDS = "REPAIR_UV_BOUNDS"
    MERGE_DUPLICATE_UV_MAPS = "MERGE_DUPLICATE_UV_MAPS"
    REMOVE_UNUSED_ASSISTANT_UV_MAPS = "REMOVE_UNUSED_ASSISTANT_UV_MAPS"
    VALIDATE_UV_MAP = "VALIDATE_UV_MAP"
    FIT_UV_ISLANDS_TO_IMAGE_REGION = "FIT_UV_ISLANDS_TO_IMAGE_REGION"
    CREATE_TEXTURE_ATLAS_LAYOUT = "CREATE_TEXTURE_ATLAS_LAYOUT"
    ASSIGN_ATLAS_TEXTURE_REGIONS = "ASSIGN_ATLAS_TEXTURE_REGIONS"
    BAKE_UV_LAYOUT_GUIDE_IMAGE = "BAKE_UV_LAYOUT_GUIDE_IMAGE"
    CREATE_UV_GRID_TEST_MATERIAL = "CREATE_UV_GRID_TEST_MATERIAL"
    CREATE_UV_MAP_VARIANT = "CREATE_UV_MAP_VARIANT"
    TAG_UV_VARIANT = "TAG_UV_VARIANT"
    CREATE_UV_COMPARISON_PREVIEW = "CREATE_UV_COMPARISON_PREVIEW"
    ACCEPT_UV_VARIANT = "ACCEPT_UV_VARIANT"
    REJECT_UV_VARIANT = "REJECT_UV_VARIANT"
    IMPORT_PBR_TEXTURE_SET = "IMPORT_PBR_TEXTURE_SET"
    CREATE_PBR_MATERIAL = "CREATE_PBR_MATERIAL"
    SET_PBR_TEXTURE_ROLE = "SET_PBR_TEXTURE_ROLE"
    GENERATE_IMAGE_ASSET = "GENERATE_IMAGE_ASSET"
    GENERATE_TEXTURE_IMAGE = "GENERATE_TEXTURE_IMAGE"
    SAVE_GENERATED_TEXTURE = "SAVE_GENERATED_TEXTURE"
    APPLY_IMAGE_TO_MATERIAL = "APPLY_IMAGE_TO_MATERIAL"
    ATTACH_GENERATED_TEXTURE = "ATTACH_GENERATED_TEXTURE"
    CREATE_PAINT_IMAGE = "CREATE_PAINT_IMAGE"
    ASSIGN_PAINT_SLOT = "ASSIGN_PAINT_SLOT"
    APPLY_TEXTURE_PAINT_STROKES = "APPLY_TEXTURE_PAINT_STROKES"
    FILL_TEXTURE_REGION = "FILL_TEXTURE_REGION"
    CREATE_BAKE_TARGET_IMAGE = "CREATE_BAKE_TARGET_IMAGE"
    BAKE_TEXTURE_PASS = "BAKE_TEXTURE_PASS"
    ASSIGN_BAKED_TEXTURE = "ASSIGN_BAKED_TEXTURE"
    ADD_DISPLACE_MODIFIER = "ADD_DISPLACE_MODIFIER"
    ADD_SMOOTH_MODIFIER = "ADD_SMOOTH_MODIFIER"
    ADD_REMESH_MODIFIER = "ADD_REMESH_MODIFIER"
    SCULPT_SMOOTH_REGION = "SCULPT_SMOOTH_REGION"
    APPLY_SCULPT_BRUSH_STROKES = "APPLY_SCULPT_BRUSH_STROKES"
    CREATE_GEOMETRY_NODES_PRESET = "CREATE_GEOMETRY_NODES_PRESET"
    SET_GEOMETRY_NODE_INPUT = "SET_GEOMETRY_NODE_INPUT"
    CREATE_GEOMETRY_NODE_GROUP_TEMPLATE = "CREATE_GEOMETRY_NODE_GROUP_TEMPLATE"
    REMOVE_GEOMETRY_NODES_MODIFIER = "REMOVE_GEOMETRY_NODES_MODIFIER"
    CREATE_GENERATED_GEOMETRY_COPY = "CREATE_GENERATED_GEOMETRY_COPY"
    CREATE_SMOOTHED_COPY = "CREATE_SMOOTHED_COPY"
    CREATE_DISPLACED_COPY = "CREATE_DISPLACED_COPY"
    CREATE_REMESHED_COPY = "CREATE_REMESHED_COPY"
    REPLACE_OBJECT_WITH_GENERATED_COPY = "REPLACE_OBJECT_WITH_GENERATED_COPY"
    CREATE_SCULPT_REGION_FROM_MATERIAL = "CREATE_SCULPT_REGION_FROM_MATERIAL"
    CREATE_SCULPT_REGION_FROM_VERTEX_GROUP = "CREATE_SCULPT_REGION_FROM_VERTEX_GROUP"
    CREATE_SCULPT_MASK = "CREATE_SCULPT_MASK"
    INVERT_SCULPT_MASK = "INVERT_SCULPT_MASK"
    CLEAR_SCULPT_MASK = "CLEAR_SCULPT_MASK"
    BLUR_SCULPT_MASK = "BLUR_SCULPT_MASK"
    SHARPEN_SCULPT_MASK = "SHARPEN_SCULPT_MASK"
    GROW_SCULPT_MASK = "GROW_SCULPT_MASK"
    SHRINK_SCULPT_MASK = "SHRINK_SCULPT_MASK"
    COMBINE_SCULPT_MASKS = "COMBINE_SCULPT_MASKS"
    CREATE_FACE_SET_FROM_MATERIAL = "CREATE_FACE_SET_FROM_MATERIAL"
    CREATE_FACE_SET_FROM_VERTEX_GROUP = "CREATE_FACE_SET_FROM_VERTEX_GROUP"
    APPLY_SCULPT_REGION_OPERATION = "APPLY_SCULPT_REGION_OPERATION"
    CREATE_DYNAMIC_TOPOLOGY_COPY = "CREATE_DYNAMIC_TOPOLOGY_COPY"
    APPLY_GENERATED_MESH_TO_OBJECT = "APPLY_GENERATED_MESH_TO_OBJECT"
    ADD_MULTIRES_MODIFIER = "ADD_MULTIRES_MODIFIER"
    CREATE_SHAPE_KEY = "CREATE_SHAPE_KEY"
    CREATE_RIG_SAFE_SHAPE_KEY = "CREATE_RIG_SAFE_SHAPE_KEY"
    SET_SHAPE_KEY_VALUE = "SET_SHAPE_KEY_VALUE"
    CREATE_PREVIEW_IMAGE = "CREATE_PREVIEW_IMAGE"
    CREATE_RENDER_PREVIEW_IMAGE = "CREATE_RENDER_PREVIEW_IMAGE"


class RiskLevel(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass(frozen=True, slots=True)
class Operation:
    operation_id: str
    type: OperationType
    payload: Mapping[str, Any]

    @property
    def target_ids(self) -> tuple[str, ...]:
        raw_targets = self.payload.get("target_ids")
        if isinstance(raw_targets, tuple):
            targets = [value for value in raw_targets if isinstance(value, str)]
        else:
            targets = []

        renames = self.payload.get("renames")
        if isinstance(renames, tuple):
            targets.extend(
                rename["target_id"]
                for rename in renames
                if isinstance(rename, Mapping) and isinstance(rename.get("target_id"), str)
            )

        for key in ("target_id", "cutter_id"):
            value = self.payload.get(key)
            if isinstance(value, str):
                targets.append(value)

        return tuple(dict.fromkeys(targets))


@dataclass(frozen=True, slots=True)
class OperationPlan:
    snapshot_id: str
    status: PlanStatus
    intent_summary: str
    assumptions: tuple[str, ...]
    questions: tuple[str, ...]
    operations: tuple[Operation, ...]


@dataclass(frozen=True, slots=True)
class RiskAssessment:
    level: RiskLevel
    requires_confirmation: bool
    reasons: tuple[str, ...]
    affected_object_count: int
